### ISSUE TITLE
Start and End properties are inaccurate

### ISSUE THREAD

**Issue by kla7** [clamsproject/app-spacy-wrapper#30]
### Bug Description

When running spacy, the `start` and `end` values for each token are inaccurate.

For example:
```
        {
          "@type": "http://vocab.lappsgrid.org/Token",
          "properties": {
            "start": 26444,
            "end": 31989,
            "pos": "DT",
            "lemma": "a",
            "text": "a",
            "id": "to_5546"
          }
        }
```

### Reproduction steps

Run spacy on any txt or mmif file.

I ran it on:
1. [Sample text from wikipedia](https://github.com/user-attachments/files/15686575/wikipedia-minecraft.txt) with the following [output MMIF](https://github.com/user-attachments/files/15686569/spacy_output.json)
2. [Whisper output MMIF](https://github.com/user-attachments/files/15686670/whisper_output.json) with the following [output MMIF](https://github.com/user-attachments/files/15686654/whisper_spacy_output.json)

### Expected behavior

The `end` value should be the `start` value + the length of the token.

**Comment by marcverhagen** [comment]
At some point some code was added to deal with pre-tokenized input to the spaCy app. This builds a token index and the length of that index is used to calculate the end offset. With non-tokenized input that index is build token by token,  and since the length of the entire index is used the first token is length 1, the second is length 2 and so on.

https://github.com/clamsproject/app-spacy-wrapper/blob/ce95ecce6f411d22133b7e780be54686cd590707/app.py#L75-L78

The code added to deal with tokenized input probably was not tested to confirm that it did the right thing with non-tokenized input.

**Comment by marcverhagen** [comment]
The "end" property is fixed, the "start" property was never wrong. Will test a little bit more before releasing a new version (specifically for pre-tokenized input).

**Comment by marcverhagen** [comment]
Well, the pretokenized parameter seems to be broken independent of what is going on in here so I will make that a separate issue.
